language:
  - go

go:
  - 1.x

install:
  - make install

script:
  - make lint

before_deploy:
  - make build
deploy:
  provider: releases
  api_key:
    secure: YUfmHD49PxkUAlhODvbxEXTDZqmk/TtvfbrJZsplsKxzC7OkxJ/iO/D1+nnY6AzPr5cKDpkvPpvVjTOHrC3NSbZszfazyowoCHPkN9K0FpCibdsNt0QAcr8uSAy7/nU0DKU/ExhzdMx1II1BrIOeAX1qTYFWY8VAEGiPm2I7/S/CalZL8DlC9MvQmSg42mMN92zGTRQUGRwoVKj5Uha25o6sPXsrUaB58YOCOmqRqccU21XsvitIT7DrNQme2WTMyyd7Cy77TbqT9QEfPpgdst7Ypcp1GQ8xELHnF011+UMUo2Rp33zI+FaQv/Blzd8ecbaYs3J1SuBwHnUd5Kp/yGm9fn0e0e7kxG6Gcl0oBMOGiFrzS4uylasLmOBgBYKdQIgBBi8eevusxsi+vV//VGU6rXe0bWL21AcMNjy8hlhwv5x7ptDtqXEkVzrAokkR6puZjKR5KfsKkqTo6W1zTUQmcyaKDCBqIkoC5KoiN4fE6ARPsIOg+2g7B+Ig5567ZITaynk5wQt1uDhFrYV061pGJGN4C41fJJomKrXyMMlT0P7hSpJCnXMGudtfo8YM39ceRmchHiPhKAiICs8LInS1NISZgAAT3JJjBZI8qCB++iBjn9w3h57/d/Voo6CgdZatbp1LTS+2yvPfVFThQSIzx+RMRlknPfgacqXZEG8=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
